### PR TITLE
Fix UPN handling

### LINKED ISSUE #150: mstsc.exe unpacked UPN-formatted credentials trailing characters
from the SSPI logs, UPN-formatted credentials (no domain, everything in user field) have trailing characters:

image (49)

"DOMAIN\user" which gets split in two parts don't suffer from the same issue:
image (48)

The bug most likely happens right after the calls to CredUnPackAuthenticationBufferW in unpack_sec_winnt_auth_identity_ex2_w

### PR DESCRIPTION
**Pull request by TheBestTvarynka**
Hi,
I fixed the UPN (user principal name) handling. closes #150 

The problem was in the trailing null characters at the end of the username buffer. In the case of UPN logon, the username buffer has two null bytes at the end.

Also, I recorded a little video demonstration:

* logon using UPN

https://github.com/Devolutions/sspi-rs/assets/43034350/1d3f99be-4d99-4cc4-8a9d-d01f19ac969b

* logon using domain + username

https://github.com/Devolutions/sspi-rs/assets/43034350/ec4ef518-6fca-487b-a35f-1f14dd9aac35

cc @awakecoding

### CODE REVIEW

File: ffi/src/utils.rs [hunk 1]
```diff
@@ -50,3 +39,16 @@ pub unsafe fn transform_credentials_handle<'a>(
...
+pub fn raw_wide_str_trim_nulls(raw_str: &mut Vec<u8>) {
+    let mut len = raw_str.len();
+    while len > 2 {
+        if raw_str[len - 2..] == [0, 0] {
+            raw_str.truncate(len - 2);
+            len = raw_str.len();
+        } else {
+            break;
+        }
+    }
```
Comment (CBenoit) [inline ffi/src/utils.rs:53]: Maybe you could add a comment explaining that it works because when encoding an UTF-16 character using two code units, the 16-bit values are chosen from the UTF-16 surrogate range 0xD800–0xDFFF, and thus only `\0` is encoded by two consecutive null bytes.

**Review by CBenoit — APPROVED** [review]
Looks good to me

**Review by CBenoit — APPROVED** [review]
